// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNPT_oG4AXLyUL6TDlaFFkHuAWOVNc8_0',
    appId: '1:944865578599:web:2b88705904eeda48bb8ec2',
    messagingSenderId: '944865578599',
    projectId: 'lebenswiki-db',
    authDomain: 'lebenswiki-db.firebaseapp.com',
    storageBucket: 'lebenswiki-db.appspot.com',
    measurementId: 'G-8JB80QDGGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXX2gHFDVn8slmhmyL9FrpPvNPDkAnQZk',
    appId: '1:944865578599:android:4cfd9ca5dff48bfdbb8ec2',
    messagingSenderId: '944865578599',
    projectId: 'lebenswiki-db',
    storageBucket: 'lebenswiki-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnIKuOhModaiP_bcNHzSJT12euludsbE',
    appId: '1:944865578599:ios:fbf216676a85d614bb8ec2',
    messagingSenderId: '944865578599',
    projectId: 'lebenswiki-db',
    storageBucket: 'lebenswiki-db.appspot.com',
    iosClientId: '944865578599-2b11ko7ohup56li2acaqhuj34i2vlk7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.lebenswikiApp',
  );
}
